### ISSUE TITLE
cppcms_tmpl_cc gives traceback issue

### ISSUE THREAD

**Issue by hoang408** [artyom-beilis/cppcms#46]
I am following [this tutorial](http://cppcms.com/wikipp/en/page/cppcms_1x_tut_hello_templates#Building.Templates).  The project was built successfully up to the end of Static Linking.

Then I want to make a custom makefile to use it with Eclipse CDT.  After much tinkering makefile and many build cycles, `cppcms_tmpl_cc` gives me a traceback issue as follow:

	$cppcms_tmpl_cc my_skin.tmpl -o my_skin.cpp
	Traceback (most recent call last):
	  File "/usr/local/bin/cppcms_tmpl_cc", line 1257, in <module>
	    main()
	  File "/usr/local/bin/cppcms_tmpl_cc", line 1160, in main
	    output_fd=open(output_file,"w")
	IOError: [Errno 2] No such file or directory: 'my_skin.cpp'

Does anyone have a way to fix this?  I plan to rebuild CppCMS as no solution has been found.

**Comment by hoang408** [comment]
`cppcms_tmpl_cc` shows up in two locations:

	$ locate cppcms_tmpl_cc
	/{homedir}/Downloads/cppcms-1.2.1/bin/cppcms_tmpl_cc
	/usr/local/bin/cppcms_tmpl_cc

I overwrite the second one with the first one (made during the build process).  Problem solved.  Does anyone know what cause my second copy to corrupt?

**Comment by hoang408** [comment]
`cppcms_tmpl_cc` shows up in two locations:

	$ locate cppcms_tmpl_cc
	/{homedir}/Downloads/cppcms-1.2.1/bin/cppcms_tmpl_cc
	/usr/local/bin/cppcms_tmpl_cc

I overwrite the second one with the first one (made during the build process).  Problem solved.  Does anyone know what cause my second copy to corrupt?
